# Generated by Django 3.2.4 on 2022-11-25 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('4bc8fe2b-d393-4a62-88be-440a91295252'), primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
